# Generated by Django 4.2.11 on 2024-03-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takehome_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fizzbuzz',
            old_name='fizzbuzz_id',
            new_name='id',
        ),
    ]
